export const distances: Record<string, number> = {
  '29. Novembra': 1800,
  'Ada Ciganlija': 5400,
  'Andrićev venac': 450,
  'Bajlonijeva pijaca': 1000,
  'Beograd na vodi': 1700,
  'Beograđanka ( centar )': 650,
  Bulbuder: 3100,
  'Bulevar Kr. Aleksandra': 5700,
  'Crveni krst': 3000,
  'Cvetanova ćuprija': 7200,
  'Cvetkova pijaca': 4100,
  'Cvetni trg': 850,
  'Dedinje (25. maj)': 4800,
  'Dedinje (Beli dvor)': 4800,
  'Dedinje (RTV Pink)': 4800,
  'Denkova bašta': 4300,
  'Donji Dorćol': 1800,
  'Dunavski kej': 2800,
  'Gornji Dorćol': 1800,
  'Gradska bolnica': 3700,
  'Gundulićev venac': 1300,
  'Južni bulevar': 2900,
  Kalemegdan: 1800,
  'Kalenić pijaca': 1900,
  'Klinički centar': 1500,
  Kluz: 5000,
  'Knez Mihajlova ( centar )': 650,
  'Kneza Miloša ( centar )': 500,
  'Kopitareva gradina': 900,
  'Kosančićev venac': 800,
  Lion: 3300,
  'Lipov lad': 3400,
  'Mali mokri lug': 7500,
  Neimar: 2200,
  'Novi Beograd': 7600,
  'Novi Beograd Blok 1 (Fontana)': 4600,
  'Novi Beograd Blok 11 (Hotel Jugoslavija)': 4300,
  'Novi Beograd Blok 11a (Opština NBG)': 4200,
  'Novi Beograd Blok 11c (Stari Merkator)': 4700,
  'Novi Beograd Blok 12 (YUBC)': 3600,
  'Novi Beograd Blok 17 (Staro sajmište)': 2100,
  'Novi Beograd Blok 19 (Sava centar)': 2700,
  'Novi Beograd Blok 19 (Sava Centar)': 2700,
  'Novi Beograd Blok 19a': 3200,
  'Novi Beograd Blok 2': 4900,
  'Novi Beograd Blok 21 (10. Gimnazija)': 2600,
  'Novi Beograd Blok 22': 3100,
  'Novi Beograd Blok 23': 3600,
  'Novi Beograd Blok 24 (Super Vero)': 4100,
  'Novi Beograd Blok 25 (Arena)': 3700,
  'Novi Beograd Blok 28 (Potkovica)': 4500,
  'Novi Beograd Blok 29': 4000,
  'Novi Beograd Blok 3': 5400,
  'Novi Beograd Blok 30 (B92)': 3600,
  'Novi Beograd Blok 31 (Merkator)': 4200,
  'Novi Beograd Blok 32 (Crkva sv. Dimitrija)': 4500,
  'Novi Beograd Blok 33 (Genex kula)': 4900,
  'Novi Beograd Blok 34 (Studentski grad)': 5300,
  'Novi Beograd Blok 37': 5700,
  'Novi Beograd Blok 38 (OŠ Ratko Mitrović)': 5500,
  'Novi Beograd Blok 4 (Politehnička akademija)': 5400,
  'Novi Beograd Blok 44 (Piramida)': 7100,
  'Novi Beograd Blok 45 (TC Enjub)': 7700,
  'Novi Beograd Blok 49': 7000,
  'Novi Beograd Blok 58': 5100,
  'Novi Beograd Blok 60 (Airport City)': 7200,
  'Novi Beograd Blok 60': 7200,
  'Novi Beograd Blok 61': 8200,
  'Novi Beograd Blok 62': 7700,
  'Novi Beograd Blok 63': 7200,
  'Novi Beograd Blok 64': 6500,
  'Novi Beograd Blok 65': 6200,
  'Novi Beograd Blok 67 (Belvil)': 5500,
  'Novi Beograd Blok 67a': 5500,
  'Novi Beograd Blok 68': 4500,
  'Novi Beograd Blok 7 (Paviljoni)': 5500,
  'Novi Beograd Blok 70 (Kineski TC)': 6200,
  'Novi Beograd Blok 70a': 5700,
  'Novi Beograd Blok 71': 8500,
  'Novi Beograd Blok 72': 8300,
  'Novi Beograd Blok 7a (Paviljoni)': 5600,
  'Novi Beograd Blok 8a': 5500,
  'Novi Beograd Blok 8a (Paviljoni)': 5500,
  'Novi Beograd Blok 9a (Dom Zdravlja)': 4800,
  'Novo groblje': 2300,
  'Obilićev venac': 600,
  Olimp: 3500,
  'Palata pravde': 1000,
  'Partizanov stadion': 3400,
  'Politika ( centar )': 600,
  Rudo: 5600,
  Sarajevska: 1200,
  'Sava mala': 500,
  'Savski trg': 600,
  'Savski venac': 4100,
  Senjak: 3100,
  'Severni bulevar': 3300,
  Skadarlija: 800,
  Slavija: 1200,
  'Slavujev venac': 2400,
  'Stari Grad': 850,
  'Studentski Trg ( centar )': 850,
  'Tehnicki fakulteti': 1400,
  'Terazije ( centar )': 0,
  'Topličin venac': 700,
  Topčider: 4700,
  'Trg Republike ( centar )': 450,
  'Učiteljsko naselje': 5200,
  'Veliki mokri lug': 8800,
  'Vračar (centar)': 1900,
  'Vračar (Centar)': 1900,
  'Vračar (Hram)': 1600,
  'Vukov spomenik': 2200,
  'Zeleni venac': 240,
  'Zeleno Brdo': 5500,
  Zira: 2100,
  Zvezdara: 7100,
  'Zvezdarska Šuma': 5000,
  'Zvezdin stadion': 3600,
  Čubura: 2400,
  'Đeram pijaca': 2400,
}

export const mlMunicipalities = [
  {
    sublocations: [
      'Crveni krst',
      'Čubura',
      'Cvetni trg',
      'Južni bulevar',
      'Kalenić pijaca',
      'Neimar',
      'Vračar (Centar)',
      'Vračar (Hram)',
    ],
    municipality: 'Vračar',
  },
  {
    sublocations: [
      'Beograđanka ( centar )',
      'Knez Mihajlova ( centar )',
      'Kneza Miloša ( centar )',
      'Politika ( centar )',
      'Stari Grad',
      'Studentski Trg ( centar )',
      'Terazije ( centar )',
      'Trg Republike ( centar )',
    ],
    municipality: 'Centar',
  },
  {
    sublocations: ['Savski venac'],
    municipality: 'Savski venac',
  },
  {
    sublocations: [
      'Bulbuder',
      'Bulevar Kr. Aleksandra',
      'Cvetanova ćuprija',
      'Cvetkova pijaca',
      'Denkova bašta',
      'Đeram pijaca',
      'Gradska bolnica',
      'Kluz',
      'Lion',
      'Lipov lad',
      'Mali mokri lug',
      'Novo groblje',
      'Olimp',
      'Rudo',
      'Severni bulevar',
      'Slavujev venac',
      'Učiteljsko naselje',
      'Veliki mokri lug',
      'Vukov spomenik',
      'Zeleno Brdo',
      'Zira',
      'Zvezdarska Šuma',
      'Zvezdara',
    ],
    municipality: 'Zvezdara',
  },
  {
    sublocations: [
      'Novi Beograd',
      'Novi Beograd Blok 1 (Fontana)',
      'Novi Beograd Blok 11 (Hotel Jugoslavija)',
      'Novi Beograd Blok 11a (Opština NBG)',
      'Novi Beograd Blok 11c (Stari Merkator)',
      'Novi Beograd Blok 12 (YUBC)',
      'Novi Beograd Blok 17 (Staro sajmište)',
      'Novi Beograd Blok 19 (Sava centar)',
      'Novi Beograd Blok 19 (Sava Centar)',
      'Novi Beograd Blok 19a',
      'Novi Beograd Blok 2',
      'Novi Beograd Blok 21 (10. Gimnazija)',
      'Novi Beograd Blok 22',
      'Novi Beograd Blok 23',
      'Novi Beograd Blok 24 (Super Vero)',
      'Novi Beograd Blok 25 (Arena)',
      'Novi Beograd Blok 28 (Potkovica)',
      'Novi Beograd Blok 29',
      'Novi Beograd Blok 3',
      'Novi Beograd Blok 30 (B92)',
      'Novi Beograd Blok 31 (Merkator)',
      'Novi Beograd Blok 32 (Crkva sv. Dimitrija)',
      'Novi Beograd Blok 33 (Genex kula)',
      'Novi Beograd Blok 34 (Studentski grad)',
      'Novi Beograd Blok 37',
      'Novi Beograd Blok 38 (OŠ Ratko Mitrović)',
      'Novi Beograd Blok 4 (Politehnička akademija)',
      'Novi Beograd Blok 44 (Piramida)',
      'Novi Beograd Blok 45 (TC Enjub)',
      'Novi Beograd Blok 49',
      'Novi Beograd Blok 58',
      'Novi Beograd Blok 60 (Airport City)',
      'Novi Beograd Blok 60',
      'Novi Beograd Blok 61',
      'Novi Beograd Blok 62',
      'Novi Beograd Blok 63',
      'Novi Beograd Blok 64',
      'Novi Beograd Blok 65',
      'Novi Beograd Blok 67 (Belvil)',
      'Novi Beograd Blok 67a',
      'Novi Beograd Blok 68',
      'Novi Beograd Blok 7 (Paviljoni)',
      'Novi Beograd Blok 70 (Kineski TC)',
      'Novi Beograd Blok 70a',
      'Novi Beograd Blok 71',
      'Novi Beograd Blok 72',
      'Novi Beograd Blok 7a (Paviljoni)',
      'Novi Beograd Blok 8a',
      'Novi Beograd Blok 8a (Paviljoni)',
      'Novi Beograd Blok 9a (Dom Zdravlja)',
    ],
    municipality: 'Novi Beograd',
  },
]
